### PR TITLE
remove extraneous condition

### PR DESCRIPTION
**Pull request by saxena-gaurav**

### CODE REVIEW

**Comment by dmlap** [comment]
How do you know this condition was extraneous?

**Comment by misteroneill** [comment]
@dmlap Because `video.parentNode` can't possibly be truthy if `video` is falsy?

**Comment by dmlap** [comment]
But video can be truthy without it having a parent node (if, for instance, the video element has been created but not attached to the document anywhere yet). I can't recall specific circumstances where that would occur but it seems weird to me that someone would have added that check without good reason.

/cc @saxena-gaurav

**Comment by misteroneill** [comment]
I considered that at first (it may have been intended to be `if (!video || !video.parentNode) {`, but `document.querySelector` won't return a node that's not in the `document` (just attempted this).

**Comment by dmlap** [comment]
@misteroneill good point there... alright, I can't think of a reason for the check either. Thanks for going over it with me.

**Pull request merged**
