### PR TITLE
Add text tracks for both video tracks and audio-only tracks

### PR DESCRIPTION
**Pull request by jamesjieye**
This is related to an issue I experienced that is the same as https://github.com/videojs/videojs-contrib-hls/issues/1255.

### CODE REVIEW

**Comment by jamesjieye** [comment]
@gesinger here is the new PR without the version changing.

**Comment by jamesjieye** [comment]
@mjneil Could you review this pull request? Thanks!

**Comment by jamesjieye** [comment]
Hi @gesinger @mjneil @BrandonOCasey,

Could you please help review this pull request and see if it is possible to get this merged?

The Travis CI build failed is due to the launching of ChromeHeadless failure. The tests itself works. I've tested it locally.

Thank you!

screen shot 2018-05-25 at 11 31 10 am

**Comment by squarebracket** [comment]
You should rebase onto current master. The testing config has been updated since you submitted this PR.

**Comment by jamesjieye** [comment]
Thank you, @squarebracket Let me rebase it

**Pull request closed without merging**
