### PR TITLE
Handle remove cues from track properly if cues is null

### PR DESCRIPTION
**Pull request by askaliuk**
https://github.com/videojs/videojs-contrib-hls/issues/892

### CODE REVIEW

**Comment by askaliuk** [comment]
@dmlap 
Looks like that was fixed in https://github.com/videojs/videojs-contrib-media-sources/commit/c2b95c56d963866190232bb87ee76ce12c21c57d ? Is it correct?

**Comment by askaliuk** [comment]
Fixed. Closing.

**Comment by dmlap** [comment]
Oops, I missed this PR when making that change. Sorry about that and thank you for taking the time to create it.

**Comment by askaliuk** [comment]
Double checked. This PR is still valid. https://github.com/videojs/videojs-contrib-media-sources/pull/113 did fix the issue.

**Comment by askaliuk** [comment]
Can I bring somebody's attention to this PR?

**Comment by forbesjo** [comment]
Looks good to me, rerunning the build then merging.

**Pull request merged**
